ALTER TABLE users ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE users ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE classes ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE classes ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE testing ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE testing ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE meetings ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE meetings ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE absence ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE absence ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE grades ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE grades ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE subject ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE subject ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE student_homework ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE student_homework ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE homework ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE homework ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE communication ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE communication ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE message ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE message ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE meals ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE meals ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE notifications ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE notifications ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE improvements ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE improvements ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();

ALTER TABLE documents ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE documents ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT now();
