name: Server
on:
  - push

jobs:
  build-linux:
    name: Linux build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21'
      - name: Get current Go version
        run: go version
      - name: Get Go dependencies
        run: go mod download
      - name: Set env
        run: go env -w GOFLAGS=-mod=mod
      - name: Change commit name in the code
        run: sed -i 's/const COMMIT_HASH = ""/const COMMIT_HASH = "${{ github.sha }}"/g' sql/config.go
      - name: Go get
        run: go get .
      - name: Build app
        run: go build -v -o MeetPlanBackend main.go
      - uses: actions/upload-artifact@v4
        with:
          name: MeetPlanBackend-linux
          path: MeetPlanBackend
  build-windows:
    name: Windows build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21'
      - name: Get current Go version
        run: go version
      - name: Get Go dependencies
        run: go mod download
      - name: Set env
        run: go env -w GOFLAGS=-mod=mod
      - name: Change commit name in the code
        shell: pwsh
        run: (Get-Content -path sql\config.go -Raw) -replace 'const COMMIT_HASH = ""','const COMMIT_HASH = "${{ github.sha }}"'
      - name: Go get
        run: go get .
      - name: Build app
        run: go build -v -o MeetPlanBackend.exe main.go
      - uses: actions/upload-artifact@v4
        with:
          name: MeetPlanBackend-windows
          path: MeetPlanBackend.exe
  docker:
    name: Docker build
    needs: build-linux
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Get Docker version
        run: docker --version
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          registry: "ghcr.io"
      - name: Downcase repository owner
        run: |
          echo REPO=$(echo ${{github.repository_owner}} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Change commit name in the code
        run: sed -i 's/const COMMIT_HASH = ""/const COMMIT_HASH = "${{ github.sha }}"/g' sql/config.go
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: "."
          file: "./Dockerfile"
          tags: ghcr.io/${{env.REPO}}/backend:latest
          push: true
